### ISSUE TITLE
Offer public API for Nippy type info

### ISSUE THREAD

**Issue by ptaoussanis** [taoensso/nippy#151]
Relevant for: #147, #140 (esp. [comment](https://github.com/ptaoussanis/nippy/issues/140#issuecomment-1187504420)).

Nippy's data format consists of 2x main parts:

1. Nippy's internal schema: mostly just the set of `[byte-id type length]` tuples.
2. The encoding of base types as per `java.io.DataOutput` and optional compression/encryption.

(1) is currently defined by a private var (`nippy/type-ids`).

The [discussion](https://github.com/ptaoussanis/nippy/issues/140#issuecomment-1187504420) on #140 concluded that it'd be useful for (1) to be made somehow public.

Just making the current `nippy/type-ids` private var public would not be ideal- we can probably offer a more convenient API to the same info.

Comments/PRs welcome for ideas, otherwise I'll try take a look at this next time I'm doing some batched work on Nippy.

**Comment by ptaoussanis** [comment]
@refset Hi Jeremy, just checking if this issue is still relevant for you?
I'm prioritising open-source work atm, and this is a candidate for one of my next tasks.

Thanks

**Comment by ptaoussanis** [comment]
@refset I had an opportunity today, so just went ahead with this.
Have pushed `[com.taoensso/nippy "3.3.0-alpha]` to Clojars with the following experimental new [var](https://github.com/ptaoussanis/nippy/blob/a92261367a323f7af6f3f883cfc64ee40842649e/src/taoensso/nippy.clj#L277).

The data format itself is described [here](https://github.com/ptaoussanis/nippy/blob/a92261367a323f7af6f3f883cfc64ee40842649e/src/taoensso/nippy.clj#L94).

From my understanding of your objective, this should hopefully allow you to write a much simpler version of your [get-len utility](https://github.com/refset/xtdb/blob/df210146d1744b14c31fa29e994ac3932c54e8d5/core/src/xtdb/nippy_utils.clj#L174).

Feedback welcome.

Cheers

**Comment by refset** [comment]
Hey @ptaoussanis - thanks a lot for this, it looks great :) we'll try to find some time to kick the tyres properly soon!
