### ISSUE TITLE
Support UUID (and inst)?

### ISSUE THREAD

**Issue by carrete** [taoensso/nippy#170]
I'm using carmine and used an uuid as the key in a call to hget with parse-map like:

```clojue
(fn [k]
  (car/wcar
    opts
    (car/parse-map (car/hget k) :keywordize)))
```

This "works" in that hget returns the expected value, but the key, an uuid in this case, is returned as nil (because `(keyword uuid)` returns nil).

Would it be possible, somehow, to support the two built-in tagged elements, uuid and inst? https://github.com/edn-format/edn?tab=readme-ov-file#built-in-tagged-elements

**Comment by ptaoussanis** [comment]
@carrete Hi Tom,

Nippy already has native support for UUIDs and `java.time.Instant`, see [here](https://github.com/taoensso/nippy/wiki/1-Getting-started#deserializing).

Could you please open this as an issue under Carmine? And to better understand exactly what trouble you're running into, it'd be helpful if you could please provide a runnable example with the relevant input data - and your expectation for the result you'd like to see.

Thanks

**Comment by carrete** [comment]
Please see https://github.com/taoensso/carmine/issues/303
