### ISSUE TITLE
A question about extend-freeze

### ISSUE THREAD

**Issue by RokLenarcic** [taoensso/nippy#174]
I see that the `custom-type-id` is hashed to 2 bytes. What happens if this collides with another extend call?

**Comment by ptaoussanis** [comment]
Hi Rok,

If `[extend-freeze](https://cljdoc.org/d/com.taoensso/nippy/CURRENT/api/taoensso.nippy#extend-freeze)` is called with 2 keywords that hash to the same id - a compile-time error will be thrown. In that case you'll need to either choose a different kw, or use the non-hashing implementation.
