### ISSUE TITLE
`[not-urgent]` Where did the name "nippy" come from?

### ISSUE THREAD

**Issue by harold** [taoensso/nippy#182]
We just had a client ask us why the files were `.nippy` files.

Can you say a few words about how the name was chosen, and what, if anything, it is referencing?

Thanks as ever for this critical library - we store, um, lots of data with it and it works perfectly. :smile:

**Comment by ptaoussanis** [comment]
@harold Hi Harold, you're very welcome - happy to hear the library has been helpful!

I'm afraid the name's unfortunately nothing too clever ^^ Nippy freezes data, and the word "nippy" can mean chilly or cold. Also there's some connotations of speed (to move quickly).

So basically - it's fast, and it's cold :-)

**Comment by harold** [comment]
Brilliant, thanks!
