### ISSUE TITLE
Thawing a frozen record returns back an older version of that Record Class

### ISSUE THREAD

**Issue by yn** [taoensso/nippy#44]
I _think_ I am having the following issue; I may be wrong, as I haven't yet tracked it down fully, but I will document it here in case someone else is having a similar issue:

1) I load up my project in Emacs with Cider, which allows live recompilation.
2) I compile a record implementation, and a method that dispatches on that record. I freeze and thaw an instance of the record. This works fine - the method dispatches correctly on the instance that is thawed.
3) I recompile the record and the method. I freeze and thaw an instance of the record. This no longer works - the method doesn't dispatch on the instance that is thawed, and claims no implementation can be found. I _think_ this is because the classloader that nippy uses somehow caches the first version of the class that it found in step 2, so I freeze an instance of a record whose Java Type is Class1-CompiledAtStep3, but when it is thawed it comes back as Class1-CompiledAtStep2.

**Comment by smee** [comment]
Just FYI: I see the same issue with Clojure 1.9.0-alpha15 and Cider 0.14.0. The classloader of a thawed instance of a defrecord instance is not the same if I reload a namespace using CIDER. I don't have enough insight yet in the classloader hierarchy to suggest a fix.
